name = "carely"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "carely-db"
database_name = "carely-db"
database_id = "4ce1b942-b175-4592-8eb7-705cdd2a8ede"

[[kv_namespaces]]
binding = "carely-kv"
id = "7ae342ee1b1043498ae0853122b961c9"

[[r2_buckets]]
binding = "carely-uploads"
bucket_name = "carely-uploads"

[vars]
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "carely-9e601"
